-- ═══════════════════════════════════════════════════════════════════
-- Migration: enable RLS on public.access_logs  (fixes rls_disabled_in_public)
-- ═══════════════════════════════════════════════════════════════════
-- Context:
--   The access_logs table is written to by the dashboard (every non-admin
--   dashboard open) and read by the admin analytics pane, but it was never
--   part of setup.sql. It was created manually, so Row-Level Security was
--   never enabled — meaning anyone with the project URL + anon key could
--   read the full activity log (emails, names, viewed dashboards) and
--   insert/delete rows.
--
--   This migration:
--     1. Ensures the table + helper function exist (safe no-op if present).
--     2. Enables RLS on access_logs.
--     3. Adds the intended policies:
--          • any authenticated user may INSERT events (the app logs as the
--            signed-in non-admin user);
--          • only admins may SELECT (the analytics pane is admin-only);
--          • no UPDATE / DELETE policies → those operations are blocked.
--
-- Safe to run on existing data: no table contents are touched.
-- Idempotent: drops legacy policies and recreates the new ones.
-- Run this in the Supabase SQL Editor.
-- ═══════════════════════════════════════════════════════════════════

-- ── 1. Helper function (same definition as setup.sql) ──────────────
-- SECURITY DEFINER bypasses RLS so the policy doesn't recurse.
create or replace function public.is_current_user_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select is_admin from public.portal_users
       where lower(email) = lower(auth.jwt()->>'email')
         and active = true
       limit 1),
    false
  );
$$;

-- ── 2. Ensure the table exists (no-op if it already does) ──────────
create table if not exists public.access_logs (
  id          bigint generated by default as identity primary key,
  user_id     uuid,
  user_email  text,
  user_name   text,
  event_type  text,
  dash_id     int,
  dash_title  text,
  sector      text,
  subsector   text,
  created_at  timestamptz default now()
);

-- ── 3. Enable Row Level Security ───────────────────────────────────
alter table public.access_logs enable row level security;

-- ── 4. Replace any legacy policies with the strict ones ────────────
drop policy if exists "read_all"             on public.access_logs;
drop policy if exists "write_anon"           on public.access_logs;
drop policy if exists "insert_authenticated" on public.access_logs;
drop policy if exists "select_admin"         on public.access_logs;

-- Any authenticated user may insert events; only admins may read them.
create policy "insert_authenticated" on public.access_logs
  for insert with check (auth.uid() is not null);
create policy "select_admin" on public.access_logs
  for select using (public.is_current_user_admin());
-- (no update / delete policies → those operations are blocked)

-- ── 5. Verify (RLS on, exactly two policies) ───────────────────────
select relname, relrowsecurity as rls_enabled
  from pg_class where relname = 'access_logs';
select schemaname, tablename, policyname, cmd
  from pg_policies
  where schemaname = 'public' and tablename = 'access_logs'
  order by policyname;
